before:
  hooks:
    - go mod tidy
builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/colima
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
