#!/usr/bin/env bash

export LIMA_INSTANCE=limakube
export CONF_DIR="$HOME/.limakube"
export LIMA_DIR="$HOME/.lima/$LIMA_INSTANCE"
export LIMA_HOME_DIR=/home/${USER}.linux # avoid using LIMA_HOME to not override Lima's behaviour.
export LAUNCHD_NAME=com.abiosoft.limakube.plist
export LAUNCHD_FILE="$HOME/Library/LaunchAgents/$LAUNCHD_NAME"
export SSH_PORT=41122
export ENABLE_KUBERNETES=""

# init
mkdir -p "$CONF_DIR"

# make room for m1 macs
export ARCH=amd64
if [ "$(uname -m)" = "arm64" ]; then
    export ARCH=arm64
fi

print_usage() (
    cat <<EOF
usage: limakube <command>

commands:
  start [--kubernetes]
    Start (and/or provision) limakube VM with docker (and kubernetes
    if --kubernetes is passed).

  stop
    Stop the limakube VM.

  delete
    Delete and teardown the limakube VM and settings.

  ssh
    SSH into the limakube VM.

  reset
    Reset the kubernetes cluster.

  -h, --help
    Show this help
EOF
    if [ -z "$1" ]; then exit 0; else exit 1; fi
)

log() (
    echo >&2 "$@"
)

config_file() (
    cat >limakube.yaml <<EOF
arch: "default"
images:
  - location: "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-arm64.img"
    arch: "aarch64"
cpus: 2
memory: "4GiB"
disk: "60GiB"
mounts:
  - location: "~"
    # CAUTION: writable SHOULD be false for the home directory.
    # Setting writable to true is possible, but untested and dangerous.
    writable: false
  - location: "/tmp/limakube"
    writable: true
ssh:
  localPort: $SSH_PORT
  loadDotSSHPubKeys: false
containerd:
  system: false
  user: false
firmware:
  legacyBIOS: false
EOF
)

assert_vm_running() (
    lima uname &>/dev/null || (echo $LIMA_INSTANCE VM is not running. Run \'$LIMA_INSTANCE start\' to start limakube && exit 1)
)

launchd_file() (
    FILE="$LAUNCHD_FILE"
    [ -f "$FILE" ] && exit 0

    cat >"$FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.abiosoft.limakube</string>
        <key>Program</key>
        <string>$CONF_DIR/socket.sh</string>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>ThrottleInterval</key>
        <integer>5</integer>
    </dict>
</plist>
EOF
)

socket_file() (
    FILE="$CONF_DIR"/socket.sh
    if [ -f "$FILE" ]; then exit 0; fi

    cat >"$FILE" <<EOF
#!/usr/bin/env bash
rm -rf "$CONF_DIR/docker.sock"
ssh -p $SSH_PORT -i ~/.lima/_config/user -o NoHostAuthenticationForLocalhost=yes -L "$CONF_DIR/docker.sock":/var/run/docker.sock -N 127.0.0.1
EOF
    chmod +x "$FILE"
)

check_deps() (
    set -eu
    command -v lima || (echo lima not found. Run 'brew install lima' to install. && exit 1)
    command -v docker || (echo docker not found. Run 'brew install docker' to install. && exit 1)
)

check_deps_k8s() (
    command -v kubectl || (echo kubectl not found. Run 'brew install kubectl' to install. && exit 1)
)

kube() (
    lima minikube "$@"
)

start_docker() (
    set +x
    lima sudo service docker start
    launchctl load "$LAUNCHD_FILE"
)

stop_docker() (
    set +x
    lima sudo service docker stop
    launchctl unload "$LAUNCHD_FILE"
)

provision_docker() (
    set +x
    if lima command -v docker; then exit 0; fi

    # socket
    echo sudo password may be required to set up Docker socket
    echo
    sudo rm -rf /var/run/docker.sock
    sudo ln -s "$CONF_DIR/docker.sock" /var/run/docker.sock
    echo Docker socket setup successful
    echo

    # docker
    lima sudo apt -y install docker.io
    lima sudo usermod -aG docker $USER

    # reset vm for user docker group to reflect
    echo restarting VM to complete Docker setup
    limactl stop $LIMA_INSTANCE
    limactl start $LIMA_INSTANCE

    # launchd for docker socket
    socket_file
    launchd_file

    # start
    start_docker
)

teardown_docker() (
    # remove socket service
    if [ -f "$LAUNCHD_FILE" ]; then
        launchctl unload $LAUNCHD_FILE
    fi
)

provision_kubeconfig() (
    set +x
    # ignore if previously provisioned
    if [ -f "$HOME/.kube/.limakube" ]; then exit 0; fi

    # ascertain deps for kubernetes
    check_deps_k8s

    # kube config
    HOST_DIR="$HOME/.kube"
    LIMA_DIR="$LIMA_HOME_DIR/.kube"
    mkdir -p "$HOST_DIR"

    # flatten in lima for portability
    lima sh -c "kubectl config view --flatten > \"$LIMA_DIR/flat-config\""

    # replace unreacheable ip with locahost
    lima sed -i 's/192.168.5.15:8443/127.0.0.1:8443/' "$LIMA_DIR/flat-config"
    # rename to limakube
    lima sed -i 's/minikube/limakube/g' "$LIMA_DIR/flat-config"
    # reverse unintended rename
    lima sed -i 's/limakube.sigs.k8s.io/minikube.sigs.k8s.io/' "$LIMA_DIR/flat-config"

    # copy to host
    limactl cp limakube:"$LIMA_DIR/flat-config" "$HOST_DIR/flat-config"

    # flatten/merge on host
    KUBECONFIG="$HOST_DIR/config":"$HOST_DIR/flat-config" kubectl config view --raw >"$HOST_DIR/lima-config"

    # backup previous config
    [ -f "$HOST_DIR/config" ] && cp "$HOST_DIR/config" "$HOST_DIR"/config-"$(date +%s)".bak

    # set combined config as new config
    cp "$HOST_DIR/lima-config" "$HOST_DIR/config"

    # set the new context
    kubectl config use-context $LIMA_INSTANCE

    # provision flag to indicate provision has been done
    touch "$HOST_DIR/.limakube"

    # clean up dirt
    rm "$HOST_DIR/lima-config"
    rm "$HOST_DIR/flat-config"
)

teardown_kubeconfig() (
    set +x
    # reset provision flag
    rm -rf "$HOME/.kube/.limakube"
    # unset kube config
    kubectl config unset users.limakube
    kubectl config unset contexts.limakube
    kubectl config unset clusters.limakube
)

start_minikube() (
    set +x
    if ! kube status; then
        kube start --driver=none
    fi
    provision_kubeconfig
)

stop_minikube() (
    set +x
    kube status || exit 0
    kube stop
)

provision_minikube() (
    set +x
    if lima command -v minikube; then exit 0; fi

    # deps
    lima sudo apt -y install conntrack

    # minikube
    lima curl -L -o /tmp/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-${ARCH}
    lima sudo install /tmp/minikube /usr/local/bin/minikube

    # kubectl
    lima curl -L -o /tmp/kubectl https://dl.k8s.io/release/v1.22.0/bin/linux/${ARCH}/kubectl
    lima sudo install /tmp/kubectl /usr/local/bin/kubectl

    # start k8s
    start_minikube
)

teardown_minikube() (
    set +x
    lima command -v minikube || exit 0

    kube delete
    teardown_kubeconfig
)

provision_vm() (
    set +x
    provision_docker
    if [ -n "$ENABLE_KUBERNETES" ]; then
        provision_minikube
    fi
)

stop_vm() (
    set -eux
    assert_vm_running
    stop_docker
    limactl stop $LIMA_INSTANCE
)

teardown_vm() (
    set -eux
    assert_vm_running

    teardown_minikube
    teardown_docker

    # delete vm
    stop_vm
    limactl delete $LIMA_INSTANCE
)

start_vm() (
    if [ "$1" = "--kubernetes" ]; then
        export ENABLE_KUBERNETES=1
    fi

    set -eux
    if [ -d "$LIMA_DIR" ]; then
        limactl start $LIMA_INSTANCE
    else
        config_file
        limactl start --tty=false limakube.yaml
        rm limakube.yaml
    fi

    provision_vm
)

lima_ssh() (
    set -eu
    assert_vm_running
    lima
)

reset_minikube() (
    set -eu
    assert_vm_running
    kube status || (echo Kubernetes is not enabled. && exit 0)
    teardown_minikube
    start_minikube
)

case "$1" in
start)
    shift
    start_vm "$@"
    ;;
stop)
    stop_vm
    ;;
delete)
    teardown_vm
    ;;
ssh)
    lima_ssh
    ;;
reset)
    reset_minikube
    ;;
-h | --help)
    print_usage
    ;;
"")
    print_usage 1
    ;;
*)
    log "invalid arg '$1'. view help with 'limakube --help'."
    exit 1
    ;;
esac
