name: Issue report
description: Report an issue
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
  - type: input
    attributes:
      label: Colima Version
      description: What is the output of `colima version`
  - type: input
    attributes:
      label: Lima Version
      description: What is the output of `limactl --version`
  - type: input
    attributes:
      label: Lima Version
      description: What is the output of `qemu-img --version`
  - type: checkboxes
    attributes:
      label: Operating System
      description: Which Operating System does this issue happen on? Check all that apply.
      options:
        - label: macOS Intel
          required: false
        - label: macOS M1
          required: false
        - label: Linux
          required: false
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Kindly walk us through the steps to reproduce this behaviour
      value: |
        1.
        2.
        3.
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
