package lima

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/abiosoft/colima/config"
	"github.com/abiosoft/colima/environment/vm/lima/limautil"
)

const (
	localhostAddr         = "127.0.0.1"
	defaultGatewayAddress = "192.168.5.2"
)

// dnsmasqProbe is the minimal package-private seam for the dnsmasq capability
// probe: it makes the guest command result, stdout, and error observable.
// *limaVM satisfies it.
type dnsmasqProbe interface {
	RunOutput(args ...string) (string, error)
}

// hasDnsmasq reports whether the guest has a loadable dnsmasq systemd service.
//
// It returns (true, nil) when the service is loaded, (false, nil) when the
// service is absent (not-found), and an error for any other load state or a
// failed guest command. It intentionally does not parse apt output, which
// misreports an installed package with an available upgrade.
func hasDnsmasq(l dnsmasqProbe) (bool, error) {
	out, err := l.RunOutput("systemctl", "show", "dnsmasq.service", "--property=LoadState", "--value")
	if err != nil {
		return false, fmt.Errorf("failed to query dnsmasq service load state: %w", err)
	}

	switch strings.TrimSpace(out) {
	case "loaded":
		return true, nil
	case "not-found":
		return false, nil
	default:
		return false, fmt.Errorf("unexpected dnsmasq service load state %q", out)
	}
}

func (l *limaVM) setupDNS(conf config.Config) error {
	present, err := hasDnsmasq(l)
	if err != nil {
		return fmt.Errorf("failed to detect dnsmasq service: %w", err)
	}
	if !present {
		// older image still using systemd-resolved
		// ignore
		return nil
	}

	// use custom gateway address
	var gatewayAddr = defaultGatewayAddress
	customGatewayAddress := conf.Network.GatewayAddress
	if customGatewayAddress != nil {
		gatewayAddr = customGatewayAddress.String()
	}

	var dnsHosts = map[string]string{
		"host.docker.internal": gatewayAddr,
		"host.lima.internal":   gatewayAddr,
	}

	internalIP := limautil.InternalIPAddress(config.CurrentProfile().ID)

	// extra dns entries
	dnsHosts["colima.internal"] = internalIP
	if (conf.Hostname) != "" {
		dnsHosts[conf.Hostname] = localhostAddr
	}

	var buf bytes.Buffer

	// generate dns hosts
	fmt.Fprintln(&buf, "# Generated by Colima")
	fmt.Fprintln(&buf, "# Do not edit this file manually")
	fmt.Fprintln(&buf)
	for k, v := range dnsHosts {
		fmt.Fprintf(&buf, "address=/%s/%s", k, v)
		fmt.Fprintln(&buf)
	}
	fmt.Fprintln(&buf) // for cleaner output

	// generate dns servers
	dnsServers := []string{gatewayAddr}
	if len(conf.Network.DNSResolvers) > 0 {
		dnsServers = nil
		for _, dns := range conf.Network.DNSResolvers {
			dnsServers = append(dnsServers, dns.String())
		}
	}
	for _, dns := range dnsServers {
		fmt.Fprintf(&buf, "server=%s", dns)
		fmt.Fprintln(&buf)
	}
	fmt.Fprintln(&buf) // for cleaner output

	// set dnsmasq listening interface and address
	fmt.Fprintln(&buf, "interface=eth0")
	fmt.Fprintln(&buf, "listen-address="+internalIP)
	fmt.Fprintln(&buf, "bind-interfaces")

	// ensure dnsmasq config directory exists
	if err := l.RunQuiet("sudo", "mkdir", "-p", "/etc/dnsmasq.d"); err != nil {
		return fmt.Errorf("failed to create dnsmasq config directory: %w", err)
	}

	// write config to dnsmasq directory
	if err := l.Write("/etc/dnsmasq.d/01-colima.conf", buf.Bytes()); err != nil {
		return fmt.Errorf("failed to write dnsmasq config: %w", err)
	}

	// remove existing resolv.conf file
	if err := l.RunQuiet("sudo", "rm", "-f", "/etc/resolv.conf"); err != nil {
		return fmt.Errorf("failed to remove existing resolv.conf: %w", err)
	}

	// replace resolv.conf with a custom one
	resolvConf := fmt.Sprintf("# Generated by Colima\n\nnameserver %s\n", internalIP)
	if err := l.Write("/etc/resolv.conf", []byte(resolvConf)); err != nil {
		return fmt.Errorf("failed to write resolv.conf: %w", err)
	}

	// restart dnsmasq service to apply changes
	if err := l.RunQuiet("sudo", "systemctl", "restart", "dnsmasq"); err != nil {
		return fmt.Errorf("failed to restart dnsmasq service: %w", err)
	}

	return nil
}
