name: golangci-lint
on:
  push:
    tags: [v*]
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.nix"
      - "**/*.lock"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.nix"
      - "**/*.lock"
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26.1"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.11.3
          args: --timeout 3m0s
